Universe                = vanilla
executable              = run.sh
arguments               = mlp mlp_pf.py pf_features.yaml /eos/user/y/ykay/WORK/samples 
output                  = batch_cpu/job.$(ClusterId).$(ProcId).out
error                   = batch_cpu/job.$(ClusterId).$(ProcId).err
log                     = batch_cpu/job.$(ClusterId).log
batch_name              = Interactive_HC_GloParT
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
#transfer_output_files   = output.tar
#transfer_output_remaps  = "output.tar = output.$(ClusterId).$(ProcId).tar"
getenv = True
request_CPUs = 64
+MaxRuntime = 200000
+AccountingGroup = "group_u_CMST3.all"
#+JobFlavour = "nextweek"
queue
